name: Add Issues to Project

on:
  issues:
    types: [opened, transferred]

jobs:
  add-to-project-issues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/cal-itp/projects/[number]
          # https://github.com/actions/add-to-project?tab=readme-ov-file#creating-a-pat-and-adding-it-to-your-repository
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
