name: Add Dependabot PRs to Project

on:
  pull_request:
    types: [opened]

jobs:
  add-to-project-dependabot:
    runs-on: ubuntu-latest
    # see https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#responding-to-events
    if: github.actor == 'dependabot[bot]'
    steps:
      - uses: actions/add-to-project@1
        with:
          project-url: https://github.com/orgs/cal-itp/projects/[number]
          # https://github.com/actions/add-to-project?tab=readme-ov-file#creating-a-pat-and-adding-it-to-your-repository
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
