# Add secret GH_PROJECT (the Project's ID) and allow org-wide secret GH_PROJECTS_TOKEN to the Dependabot secrets in the repo

name: Add Dependabot PRs to Project

on:
  pull_request:
    types: [opened]

jobs:
  add-to-project-dependabot:
    runs-on: ubuntu-latest
    # see https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#responding-to-events
    if: github.actor == 'dependabot[bot]'
    steps:
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/cal-itp/projects/${{ secrets.GH_PROJECT }}
          github-token: ${{ secrets.GH_PROJECTS_TOKEN }}
